apiVersion: apps/v1
kind: Deployment
metadata:
  name: veiculos-service
spec:
  replicas: 3
  selector:
    matchLabels:
      app: veiculos-service
  template:
    metadata:
      labels:
        app: veiculos-service
    spec:
      containers:
        - name: veiculos-container
          image: veiculos-at/veiculos
          ports:
            - containerPort: 3000
          env:
            - name: SPRING_PROFILES_ACTIVE
              value: prod
            - name: MONGO_URI
              value: mongodb://mongo-server:27017/veiculosdb
            - name: EUREKA_SERVER_URL
              value: http://eureka-server:8761/eureka