apiVersion: v1
kind: Service
metadata:
  name: veiculos-service
spec:
  selector:
    app: veiculos-service
  ports:
    - protocol: TCP
      port: 80
      targetPort: 3000  # Porta interna do contêiner
  type: LoadBalancer  # Balanceamento de carga